<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <property name="safety_offset" value="0.08"/>
  
  <xacro:include filename="$(find schunk_description)/urdf/lwa4d/lwa4d.gazebo.xacro" />
  <xacro:include filename="$(find schunk_description)/urdf/lwa4d/lwa4d.transmission.xacro" />

  <xacro:macro name="schunk_lwa4d" params="parent name *origin">

    <!-- joint between base_link and arm_0_link -->
    <joint name="${name}_0_joint" type="fixed" >
      <insert_block name="origin" />
      <parent link="${parent}" />
      <child link="${name}_0_link" />
    </joint>
    
    <link name="${name}_0_link">
      <xacro:default_inertial/>	
      <!--inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1.0"/>
        <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
      </inertial-->

      <visual>
        <origin xyz="0 0 0.004" rpy="0 0 0" />
        <geometry>
          <cylinder radius="0.045" length="0.08"/>
        </geometry>
        <material name="Schunk/Black" />
      </visual>

      <collision>
        <origin xyz="0 0 0.005" rpy="0 0 0" />
        <geometry>
          <box size="0.01 0.01 0.01"/>
        </geometry>
      </collision>
    </link>

    <!-- joint between arm_0_link and arm_1_link -->
    <joint name="${name}_1_joint" type="revolute">
      <origin xyz="0 0 0.15" rpy="0 -${M_PI} ${M_PI}"/>
      <parent link="${name}_0_link"/>
      <child link="${name}_1_link"/>
      <axis xyz="0 0 1"/>
      <limit effort="216" velocity="0.43633" lower="${-M_PI+safety_offset}" upper="${M_PI-safety_offset}"/>
    </joint>

    <link name="${name}_1_link">
      <xacro:default_inertial/>	
      <!--inertial>
        <origin xyz="0 0 0" rpy="0 0 0" /-->
        <!--mass value="5.9907"/-->
        <!--mass value="2.0"/>
        <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
      </inertial-->
      
      <visual>
        <origin xyz="0 0 -0.15" rpy="0 0 ${M_PI}" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4d/arm_1_link.stl" />
        </geometry>
        <material name="Schunk/LightGrey" />
      </visual>
      
      <collision>
        <origin xyz="0 0 -0.15" rpy="0 0 ${M_PI}" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4d/arm_1_link.stl" />
        </geometry>
      </collision>
    </link>

    <!-- joint between arm_1_link and arm_2_link -->  
    <joint name="${name}_2_joint" type="revolute">
      <origin xyz="0 0 -0.15" rpy="-${M_PI/2} 0 0"/>
      <parent link="${name}_1_link"/>
      <child link="${name}_2_link"/>
      <axis xyz="0 0 1"/>
      <limit effort="216" velocity="0.43633" lower="${-2.14 + safety_offset}" upper="${2.14 - safety_offset}"/>
    </joint>

    <link name="${name}_2_link">
      <xacro:default_inertial/>	
      <!--inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="2.0"/>
        <inertia ixx="0.03" ixy="0" ixz="0" iyy="0.03" iyz="0" izz="0.03" />
      </inertial-->
      
      <visual>
        <origin xyz="0 0 0" rpy="0 0 ${M_PI}" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4d/arm_2_link.stl" />
        </geometry>
        <material name="Schunk/Black" />
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="0 0 ${M_PI}" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4d/arm_2_link.stl" />
        </geometry>
      </collision>
    </link>

    <!-- joint between arm_2_link and arm_3_link -->  
    <joint name="${name}_3_joint" type="revolute">
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
      <parent link="${name}_2_link"/>
      <child link="${name}_3_link"/>
      <axis xyz="0 0 1"/>
      <limit effort="81.5" velocity="0.4189" lower="${-M_PI + safety_offset}" upper="${M_PI - safety_offset}"/>
    </joint>

    <link name="${name}_3_link">
      <xacro:default_inertial/>	
      <!--inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="2.0"/>
        <inertia ixx="0.03" ixy="0" ixz="0" iyy="0.03" iyz="0" izz="0.03" />
      </inertial-->
      
      <visual>
        <origin xyz="0 0 -0.328" rpy="0 0 ${M_PI}" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4d/arm_3_link.stl" />
        </geometry>
        <material name="Schunk/LightGrey" />
      </visual>
      
      <collision>
        <origin xyz="0 0 -0.328" rpy="0 0 ${M_PI}" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4d/arm_3_link.stl" />
        </geometry>
      </collision>
    </link>  

    <!-- joint between arm_3_link and arm_4_link -->
    <joint name="${name}_4_joint" type="revolute">
      <origin xyz="0 0 -0.328" rpy="-${M_PI/2} 0 0"/>
      <parent link="${name}_3_link"/>
      <child link="${name}_4_link"/>
      <axis xyz="0 0 1"/>
      <limit effort="81.5" velocity="0.4189" lower="${-2.18 + safety_offset}" upper="${2.18 - safety_offset}"/>
    </joint>

    <link name="${name}_4_link">
      <xacro:default_inertial/>	
      <!--inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="2.0"/>
        <inertia ixx="0.03" ixy="0" ixz="0" iyy="0.03" iyz="0" izz="0.03" />
      </inertial-->
      
      <visual>
        <origin xyz="0 0 0" rpy="0 0 ${M_PI}" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4d/arm_4_link.stl" />
        </geometry>
        <material name="Schunk/Black" />
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="0 0 ${M_PI}" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4d/arm_4_link.stl" />
        </geometry>
      </collision>
    </link>

    <!-- joint between arm_4_link and arm_5_link -->
    <joint name="${name}_5_joint" type="revolute">
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      <parent link="${name}_4_link"/>
      <child link="${name}_5_link"/>
      <axis xyz="0 0 1"/>
      <limit effort="20.7" velocity="0.43633" lower="${-M_PI + safety_offset}" upper="${M_PI - safety_offset}"/>
    </joint>

    <link name="${name}_5_link">
      <xacro:default_inertial/>	
      <!--inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="2.313272"/>
        <inertia ixx="0.03" ixy="0" ixz="0" iyy="0.03" iyz="0" izz="0.03" />
      </inertial-->
      
      <visual>
        <origin xyz="0 0 -0.323" rpy="0 0 ${M_PI}" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4d/arm_5_link.stl" />
        </geometry>
        <material name="Schunk/LightGrey" />
      </visual>
      
      <collision>
        <origin xyz="0 0 -0.323" rpy="0 0 ${M_PI}" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4d/arm_5_link.stl" />
        </geometry>
      </collision>
    </link>

    <!-- joint between arm_5_link and arm_6_link -->
    <joint name="${name}_6_joint" type="revolute">
      <origin xyz="0 0 -0.323" rpy="-${M_PI/2} 0 0" />
      <parent link="${name}_5_link"/>
      <child link="${name}_6_link"/>
      <axis xyz="0 0 1"/>
      <limit effort="15" velocity="1.2566" lower="${-2.09 + safety_offset}" upper="${2.09 - safety_offset}"/>
    </joint>

    <link name="${name}_6_link">
      <xacro:default_inertial/>	
      <!--inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="2.057856"/>
        <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
      </inertial-->
      
      <visual>
        <origin xyz="0 0 0" rpy="0 ${M_PI} 0" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4d/arm_6_link.stl" />
        </geometry>
        <material name="Schunk/Black" />
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="0 ${M_PI} 0" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4d/arm_6_link.stl" />
        </geometry>
      </collision>
    </link>

    <!-- joint between arm_6_link and arm_7_link -->
    <joint name="${name}_7_joint" type="revolute">
      <origin xyz="0 0 0" rpy="-${M_PI/2} 0 0" />
      <parent link="${name}_6_link"/>
      <child link="${name}_7_link"/>
      <axis xyz="0 0 1"/>
      <limit effort="15" velocity="1.2566" lower="${-2.96 + safety_offset}" upper="${2.96 - safety_offset}"/>
    </joint>

    <link name="${name}_7_link">
      <xacro:default_inertial/>	
      <!--inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1.120198"/>
        <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
      </inertial-->
      
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4d/arm_7_link.stl" />
        </geometry>
        <material name="Schunk/LightGrey" />
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://schunk_description/meshes/lwa4d/arm_7_link.stl" />
        </geometry>
      </collision>
    </link>

    <!-- extensions -->
    <xacro:schunk_lwa4d_gazebo name="${name}" />
    <xacro:schunk_lwa4d_transmission name="${name}" />

  </xacro:macro>

</robot>
